# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    env:
      INTEGRATION: openldap
    runs-on: ubuntu-latest
    services:
      openldap:
        image: osixia/openldap:1.3.0
        env:
          LDAP_TLS_VERIFY_CLIENT: try
        ports:
          - 389:389
          - 636:636
        # volumes:
        #   - "$(pwd)"/test/fixtures/ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom
    strategy:
      matrix:
        ruby:
          - "2.5"
          - "2.6"
          - "2.7"
          - "jruby-9.2"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby }}
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: ${{ matrix.ruby }}
    # - name: Create OpenLDAP container
    #   run: ->
    #     docker run \
    #     --hostname ldap.example.org \
    #     --env LDAP_TLS_VERIFY_CLIENT=try \
    #     -p 389:389 \
    #     -p 636:636 \
    #     -v "$(pwd)"/test/fixtures/ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom \
    #     --name openldap \
    #     --detach \
    #     osixia/openldap:1.3.0 \
    #       --copy-service \
    #       --loglevel debug \
    - name: Install dependencies
      run: pwd; bundle install
    - name: Run tests
      run: bundle exec rake ci
